"""initial schema

Revision ID: a4aeeb280392
Revises: 
Create Date: 2026-09-26 13:55:00.145731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4aeeb280392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_practice_id'), 'owners', ['practice_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_services_price_non_negative'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_practice_id'), 'services', ['practice_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('practice_id', 'email', name='uq_users_practice_id_email')
    )
    op.create_index(op.f('ix_users_practice_id'), 'users', ['practice_id'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pets_practice_id'), 'pets', ['practice_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_pet_id'), 'visits', ['pet_id'], unique=False)
    op.create_index(op.f('ix_visits_practice_id'), 'visits', ['practice_id'], unique=False)
    op.create_index(op.f('ix_visits_user_id'), 'visits', ['user_id'], unique=False)
    op.create_index(op.f('ix_visits_visit_date'), 'visits', ['visit_date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'other')", name='ck_payments_method'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_practice_id'), 'payments', ['practice_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('visit_id', sa.Uuid(), nullable=True),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False),
    sa.Column('administered_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('next_due_date IS NULL OR next_due_date >= administered_date', name='ck_vaccinations_due_not_before_administered'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_next_due_date'), 'vaccinations', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_vaccinations_pet_id'), 'vaccinations', ['pet_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_practice_id'), 'vaccinations', ['practice_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_visit_id'), 'vaccinations', ['visit_id'], unique=False)
    op.create_table('visit_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_visit_items_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_visit_items_subtotal_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_visit_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_items_service_id'), 'visit_items', ['service_id'], unique=False)
    op.create_index(op.f('ix_visit_items_visit_id'), 'visit_items', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_items_visit_id'), table_name='visit_items')
    op.drop_index(op.f('ix_visit_items_service_id'), table_name='visit_items')
    op.drop_table('visit_items')
    op.drop_index(op.f('ix_vaccinations_visit_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_practice_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_pet_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_next_due_date'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_payments_practice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_visits_visit_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_user_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_practice_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_pet_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_pets_practice_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_users_practice_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_practice_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_owners_practice_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('practices')
    # ### end Alembic commands ###
